
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/golang-exemplos/k8s-gcp:latest', '-t', 'gcr.io/golang-exemplos/k8s-gcp:$SHORT_SHA','.']

  - name: 'docker'
    args: ['run','-d','--name','goapp','gcr.io/golang-exemplos/k8s-gcp:latest']

  - name: 'docker'
    args: ['exec','goapp','go','test']