
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/golang-k8s-gcp/teste:latest', '-t', 'gcr.io/golang-k8s-gcp/teste:$SHORT_SHA','.']

  - name: 'docker'
    args: ['run','-d','--name','goapp','gcr.io/golang-k8s-gcp/teste:latest']

  - name: 'docker'
    args: ['exec','goapp','go','test']